In [99]:
import pandas as pd

In [100]:
df = pd.read_csv('test.csv')

In [101]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB

In [103]:
# Handle missing values function
def handle_missing_values(df):
    
    # Fill numeric columns with mean
    for col in df.select_dtypes(include=["int64", "float64"]).columns:
        df[col] = df[col].fillna(df[col].mean())
    
    # Fill categorical columns with most frequent value (mode)
    for col in df.select_dtypes(include=["object"]).columns:
        df[col] = df[col].fillna(df[col].mode()[0])
    
    return df



df = handle_missing_values(df)

C:\Users\ELITEBOOK\AppData\Local\Temp\ipykernel_5788\2309162341.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].mode()[0])

In [104]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [105]:


def object_into_int(lis):
    for i in lis:
        data =pd.DataFrame({i:df[i].unique()})
        data_le=LabelEncoder()
        data_le.fit(np.ravel(data))
        df[i]=data_le.transform(df[i])
obj=["HomePlanet","Cabin","Destination","CryoSleep","VIP"]
object_into_int(obj)

In [106]:
def float_into_int(lis):
    for i in lis:
       df[i]= df[i].astype("int64")
    
fl=['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
float_into_int(fl)

In [107]:
df.describe()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,4277.000000,4277.000000,4277.000000,4277.000000,4277.000000,4277.000000,4277.000000,4277.000000,4277.000000,4277.000000,4277.00000
mean,0.666823,0.361001,1598.947861,1.516016,28.644143,0.017302,219.261164,439.472294,177.288754,303.051204,310.69675
std,0.809240,0.480347,993.324220,0.801973,14.027705,0.130409,601.162848,1508.609203,554.357253,1103.913087,1235.27461
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,0.000000,0.000000,664.000000,1.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,0.000000,0.000000,1610.000000,2.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,1.000000,1.000000,2515.000000,2.000000,37.000000,0.000000,79.000000,143.000000,51.000000,83.000000,53.00000
max,2.000000,1.000000,3264.000000,2.000000,79.000000,1.000000,11567.000000,25273.000000,8292.000000,19844.000000,22272.00000

In [108]:
df.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
dtype: int64

In [109]:
columns_to_remove = [ "Name", "Cabin"]

df = df.drop(columns_to_remove, axis=1)

In [110]:
ids = ["PassengerId"]
df = df.drop(ids, axis=1)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    4277 non-null   int64
 1   CryoSleep     4277 non-null   int64
 2   Destination   4277 non-null   int64
 3   Age           4277 non-null   int64
 4   VIP           4277 non-null   int64
 5   RoomService   4277 non-null   int64
 6   FoodCourt     4277 non-null   int64
 7   ShoppingMall  4277 non-null   int64
 8   Spa           4277 non-null   int64
 9   VRDeck        4277 non-null   int64
dtypes: int64(10)
memory usage: 334.3 KB

In [112]:
df.to_csv('test_cleaned.csv', index=False)

In [113]:
df1 = pd.read_csv('train.csv')

In [114]:
df1.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [115]:
# Handle missing values function
def handle_missing_values(df1):
    
    # Fill numeric columns with mean
    for col in df1.select_dtypes(include=["int64", "float64"]).columns:
        df1[col] = df1[col].fillna(df1[col].mean())
    
    # Fill categorical columns with most frequent value (mode)
    for col in df1.select_dtypes(include=["object"]).columns:
        df1[col] = df1[col].fillna(df1[col].mode()[0])
    return df1

df1 = handle_missing_values(df1)

C:\Users\ELITEBOOK\AppData\Local\Temp\ipykernel_5788\3029945882.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1[col] = df1[col].fillna(df1[col].mode()[0])

In [116]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8693 non-null   object
 2   CryoSleep     8693 non-null   bool
 3   Cabin         8693 non-null   object
 4   Destination   8693 non-null   object
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   bool
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(3), float64(6), object(5)
memory usage: 772.7+ KB

In [117]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [118]:
def object_into_int(lis):
    for i in lis:
        data =pd.DataFrame({i:df1[i].unique()})
        data_le=LabelEncoder()
        data_le.fit(np.ravel(data))
        df1[i]=data_le.transform(df1[i])
obj=["HomePlanet","Cabin","Destination","CryoSleep","VIP",]
object_into_int(obj)

In [119]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8693 non-null   int64
 2   CryoSleep     8693 non-null   int64
 3   Cabin         8693 non-null   int64
 4   Destination   8693 non-null   int64
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   int64
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), int64(5), object(2)
memory usage: 891.5+ KB

In [120]:
def float_into_int(lis):
    for i in lis:
       df1[i]= df1[i].astype("int64")
    
fl=['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
float_into_int(fl)

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    4277 non-null   int64
 1   CryoSleep     4277 non-null   int64
 2   Destination   4277 non-null   int64
 3   Age           4277 non-null   int64
 4   VIP           4277 non-null   int64
 5   RoomService   4277 non-null   int64
 6   FoodCourt     4277 non-null   int64
 7   ShoppingMall  4277 non-null   int64
 8   Spa           4277 non-null   int64
 9   VRDeck        4277 non-null   int64
dtypes: int64(10)
memory usage: 334.3 KB

In [122]:
df1.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

In [123]:
df1.describe()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000,8693.000000
mean,0.649833,0.349362,3218.609341,1.494306,28.810882,0.022892,224.673300,458.075578,173.711722,311.135856,304.836305
std,0.795183,0.476796,2003.884349,0.814966,14.339536,0.149568,659.739371,1594.434978,597.417450,1124.675871,1133.259056
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1341.000000,1.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,3218.000000,2.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,5018.000000,2.000000,37.000000,0.000000,78.000000,118.000000,45.000000,89.000000,71.000000
max,2.000000,1.000000,6559.000000,2.000000,79.000000,1.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [124]:
columns_to_remove = [ "Name", "Cabin"]

df1 = df1.drop(columns_to_remove, axis=1)

In [125]:
ids = ["PassengerId"]
df1 = df1.drop(ids, axis=1)

In [126]:
print("ids")

ids

In [127]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8693 non-null   int64
 1   CryoSleep     8693 non-null   int64
 2   Destination   8693 non-null   int64
 3   Age           8693 non-null   int64
 4   VIP           8693 non-null   int64
 5   RoomService   8693 non-null   int64
 6   FoodCourt     8693 non-null   int64
 7   ShoppingMall  8693 non-null   int64
 8   Spa           8693 non-null   int64
 9   VRDeck        8693 non-null   int64
 10  Transported   8693 non-null   bool
dtypes: bool(1), int64(10)
memory usage: 687.8 KB

In [128]:
val = df1["Transported"].fillna(0).astype(int)

In [129]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [130]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [131]:
y = train['Transported']
X = train.drop(columns=['Transported','PassengerId','Name'])
test_ids = test['PassengerId']
X_test = test.drop(columns=['PassengerId','Name'])

In [132]:
num_cols = X.select_dtypes(include=['int64','float64']).columns
cat_cols = X.select_dtypes(include=['object','bool']).columns

num_imputer = SimpleImputer(strategy='median')
cat_imputer = SimpleImputer(strategy='most_frequent')

X[num_cols] = num_imputer.fit_transform(X[num_cols])
X_test[num_cols] = num_imputer.transform(X_test[num_cols])

X[cat_cols] = cat_imputer.fit_transform(X[cat_cols])
X_test[cat_cols] = cat_imputer.transform(X_test[cat_cols])

In [133]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)

X[cat_cols] = encoder.fit_transform(X[cat_cols])
X_test[cat_cols] = encoder.transform(X_test[cat_cols])

In [134]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

preds = model.predict(X_val)
print("Validation Accuracy:", accuracy_score(y_val, preds))

Validation Accuracy: 0.7745830937320299

In [135]:
model.fit(X, y)

test_preds = model.predict(X_test)

submission = pd.DataFrame({
    'PassengerId': test_ids,
    'Transported': test_preds
})

submission.to_csv('submission.csv', index=False)
submission.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True

Upload **submission.csv** to Kaggle Spaceship Titanic competition.